const FETCH_ITEMS_REQUEST = "FETCH_ITEMS_REQUEST";
const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
const FETCH_ITEMS_FAILURE = "FETCH_ITEMS_FAILURE";
const SHOW_MODAL = "SHOW_MODAL";
const PASS_MODAL_INNER = "PASS_MODAL_INNER";
const REQUEST_LOCAL_STORAGE_FAVORITES = "REQUEST_LOCAL_STORAGE_FAVORITES";
const REQUEST_LOCAL_STORAGE_CART = "REQUEST_LOCAL_STORAGE_CART";

export {
  FETCH_ITEMS_REQUEST,
  FETCH_ITEMS_SUCCESS,
  FETCH_ITEMS_FAILURE,
  SHOW_MODAL,
  PASS_MODAL_INNER,
  REQUEST_LOCAL_STORAGE_FAVORITES,
  REQUEST_LOCAL_STORAGE_CART,
};
